
server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tharinduyasarathna27/inventory-servers/tree/master/cloud-config-repo-store
          search-paths:
           - '*service'
        
