server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kasunguruge/spring-cloud-config-store-gpg
          search-paths:
           - '*service'
