
server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tharinduyasarathna27/spring-cloud-config-store
          search-paths:
            - '*service'

          force-pull: true





   
