
server:
  port: 8091
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kasunguruge/spring-cloud-config-store
          search-paths:
           - '*service'

   
